const {
  LANDING_PAD,
  CAPSULES_URL,
  BASE_PATH,
  CAPSULES_END_POINT_PATH,
  LANDING_PAD_END_POINT_PATH,
  LANDING_PAD_SELECT_QUERY,
  LANDING_PAD_INSERT_QUERY
} = require("./constant");

module.exports = {
  LANDING_PAD,
  CAPSULES_URL,
  BASE_PATH,
  CAPSULES_END_POINT_PATH,
  LANDING_PAD_END_POINT_PATH,
  LANDING_PAD_SELECT_QUERY,
  LANDING_PAD_INSERT_QUERY
};
